question_data = [
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Science: Computers",
                "question": "RAM stands for Random Access Memory.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Science: Computers",
                "question": "The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Science: Computers",
                "question": "All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Science: Computers",
                "question": "The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "hard",
                "category": "Science: Computers",
                "question": "The T-Mobile Sidekick smartphone is a re-branded version of the Danger Hiptop.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Science: Computers",
                "question": "Linus Torvalds created Linux and Git.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Science: Computers",
                "question": "The first dual-core CPU was the Intel Pentium D.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "easy",
                "category": "Science: Computers",
                "question": "Time on Computers is measured via the EPOX System.",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Science: Computers",
                "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
                "correct_answer": "True",
                "incorrect_answers": ["False"],
            },
            {
                "type": "boolean",
                "difficulty": "medium",
                "category": "Science: Computers",
                "question": "A Boolean value of &quot;0&quot; represents which of these words?",
                "correct_answer": "False",
                "incorrect_answers": ["True"],
            },
        ]
